baseurl = "https://nmarcetic.com"
title = "Nikola Marcetic | Building in Web3 / DeFi"

theme = "coder-portfolio"

publishDir = "docs"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Nikola Marcetic"
    description = "Nikola's Website - Senior Software Developer / Web3 | DeFi"
    keywords = "senior developer, solution architect, Europe, Serbia, freelance, consultancy, cloud-native, nmarcetic, DeFi, work, Crypto"
    info = "TRAILBLAZING ON-CHAIN FINANCE."
    position = "Web3 / DeFi Engineer — Distributed Systems · Blockchain Infrastructure · Performance"
    avatarurl = "images/me_avatar.png"
    footercontent = "If I press a keyboard keys in the right order, I can do anything!"
    fixedbarContent = ""
    fixedbarContentAfter = "Thank You! Please share it if you like it→"
    googleAnalytics = "G-4YZ20LHWWE"

    hideCredits = false
    hideCopyright = false

    # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true
    enableFacebookShare = false
    enableHatenaShare = false
    enableLineShare = false
    enableLinkedInShare = true

    thumbnail = "images/avatar.jpg"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/nmarcetic/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/n_marcetic/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/marcetic/"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Nikola Marcetic"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Nikola Marcetic"
            info = "TRAILBLAZING ON-CHAIN FINANCE."
            description = "Nikola's personal website"
            keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "about"
            [[languages.en.menu.main]]
                name = "Lab"
                weight = 2
                url = "lab"
            [[languages.en.menu.main]]
                name = "Resume"
                weight = 3
                url = "pdf/Nikola_CV.pdf"
            [[languages.en.menu.main]]
                name = "Connect"
                weight = 4
                url = "connect"
